title: TrainBuilder
desc: TODO
role: Developer
begin_year: 2007
end_year: 2007
_links:
  languages:
    - title: C#
      href: /languages/cs/

    - title: SQL
      href: /languages/sql/

  db:
    - title: SQL Server
      href: /db/sql-server/

  os:
    - title: Windows
      href: /os/windows/
